#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 12 20:29:02 GMT+03:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
