#LazyRAM ABSOLUTE automatic optimizer (no GUI / no keybinds)
#Sat Sep 12 22:41:44 GMT+03:00 2026
afkDropParticles=true
afkFreeze=true
afkFreezeSingleplayerSimulation=true
afkGcOnEnter=true
afkSeconds=60
bakedQuadDedup=true
blockStateFaceArrayDedup=true
compactCanonicalEngine=true
compactModelFaceLists=true
compactStateNeighbours=true
diskColdIndex=true
emptyDataComponentMapReuse=true
explicitGcOnCritical=true
hangWatchdog=true
hangWatchdogSeconds=45
heapPressureEngine=true
instantCrashExit=true
leakGrowthMiB=384
leakSentinel=true
multipartModelDedup=true
multipartPredicateCache=true
variantStringDedup=true
voxelShapeDedup=true
